const ConstantsAdminReviewsEditor = {
  SELECT_OPTION: "ADMIN_REVIEWS_EDITOR_SELECT_OPTION",
  SET_AUTOCOMPLETE_SUGGESTIONS: "ADMIN_REVIEWS_EDITOR_SET_AUTOCOMPLETE_SUGGESTIONS",
  UPDATE_REVIEW: "ADMIN_REVIEWS_EDITOR_UPDATE_REVIEW",
  QUERY_REVIEWS_BY_TITLE_EXACT: "ADMIN_REVIEWS_EDITOR_QUERY_SEARCH_RESULTS_BY_TITLE",
};

export default ConstantsAdminReviewsEditor;