const ConstantsAdminReviewsSearch = {
  GET_ALL_REVIEWS: "ADMIN_REVIEWS_GET_REVIEWS",
  GET_REVIEWS_FAILURE: "ADMIN_REVIEWS_GET_REVIEWS_FAILURE",
  GET_REVIEWS_SUCCESS: "ADMIN_REVIEWS_GET_REVIEWS_SUCCESS",
  SET_AUTOCOMPLETE_SUGGESTIONS: "ADMIN_REVIEWS_SET_AUTOCOMPLETE_SUGGESTIONS",
  SET_INPUT: "ADMIN_REVIEWS_SET_INPUT",
  QUERY_REVIEWS_BY_TITLE: "ADMIN_REVIEWS_QUERY_RESULTS",
  QUERY_REVIEWS_BY_TITLE_FAILURE: "ADMIN_REVIEWS_QUERY_RESULTS_FAILURE",
  QUERY_REVIEWS_BY_TITLE_SUCCESS: "ADMIN_REVIEWS_QUERY_RESULTS_SUCCESS",
};

export default ConstantsAdminReviewsSearch;